RoadStones Market/Controllers/CartController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using RoadStones_Data.Data;
using RoadStones_Data.Data.Repository.IRepository;
using RoadStones_Models;
using RoadStones_Models.ViewModels;
using RoadStones_Utility;
using RoadStones_Utility.BrainTree;

namespace RoadStones_Market.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        [BindProperty] 
        public ProductUserVM ProductUserVm { get; set; }

        
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;
        private readonly IApplicationUserRepository _applicationUser;
        private readonly IProductRepository _productRepository;
        private readonly IInquiryHeaderRepository _inquiryHeader;
        private readonly IInquiryDetailsRepository _inquiryDetails;
        private readonly IOrderHeaderRepository _orderHeaderRepository;
        private readonly IOrderDetailRepository _orderDetailRepository;
        private readonly IBrainTreeGate _brain;
        

        public CartController( IWebHostEnvironment webHostEnvironment, IEmailSender emailSender, IApplicationUserRepository applicationUser, IProductRepository productRepository, IInquiryHeaderRepository inquiryHeader, IInquiryDetailsRepository inquiryDetails, IOrderDetailRepository orderDetailRepository, IOrderHeaderRepository orderHeaderRepository, IBrainTreeGate brain)
        {
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _applicationUser = applicationUser;
            _inquiryHeader = inquiryHeader;
            _inquiryDetails = inquiryDetails;
            _orderDetailRepository = orderDetailRepository;
            _orderHeaderRepository = orderHeaderRepository;
            _brain = brain;
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart)!=null
            && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart).Any())
            {
                //Session exists
                shoppingCartList = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart).ToList();
            }

            List<int> productsIdsInCart = shoppingCartList.Select(x => x.ProductId).ToList();

            IEnumerable<Product> productsListTemp = _productRepository.GetAll(p => productsIdsInCart.Contains(p.Id));
            List<Product> productsList= new List<Product>();

            foreach (var shoppingCart in shoppingCartList)
            {
                Product productTemp = productsListTemp.FirstOrDefault(u => u.Id == shoppingCart.ProductId);
                productTemp.TempSqMeters = shoppingCart.SqMeters;
                productsList.Add(productTemp);
            }
            
            return View(productsList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Product> prodList)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            
            foreach (var product in prodList)
            {
                shoppingCartList.Add(new ShoppingCart
                {
                    ProductId = product.Id,
                    SqMeters = product.TempSqMeters
                });
            }
            HttpContext.Session.Set(WebConstants.SessionCart, shoppingCartList);
            return RedirectToAction(nameof(Summary));
        }

        public IActionResult Summary()
        {
            ApplicationUser appUser;

            if (User.IsInRole(WebConstants.AdminRole))
            {
                if (HttpContext.Session.Get<int>(WebConstants.SessionInquiryId) != 0)
                {
                    //cart has been loaded using an inquiry
                    InquiryHeader inquiryHeader = _inquiryHeader.FirstOrDefault(u =>
                        u.Id == HttpContext.Session.Get<int>(WebConstants.SessionInquiryId));

                    appUser = new ApplicationUser()
                    {
                        Email = inquiryHeader.Email,
                        FullName = inquiryHeader.FullName,
                        PhoneNumber = inquiryHeader.PhoneNumber
                    };
                }
                else
                {
                    appUser = new ApplicationUser();
                }

                var gateway = _brain.GetGateway();
                var clientToken = gateway.ClientToken.Generate();

                ViewBag.ClientToken = clientToken;

            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;

                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                appUser = _applicationUser.FirstOrDefault(u => u.Id == claim.Value);
            }

           

            // var userId = User.FindFirstValue(ClaimTypes.Name); --> Another way to retrive UserId

            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart).Any())
            {
                //Session exists
                shoppingCartList = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstants.SessionCart).ToList();
            }

            List<int> productsIdsInCart = shoppingCartList.Select(x => x.ProductId).ToList();

            IEnumerable<Product> productsList = _productRepository.GetAll(p => productsIdsInCart.Contains(p.Id));

            ProductUserVm = new ProductUserVM()
            {
                ApplicationUser = appUser,
               
            };

            foreach (var cartObj in shoppingCartList)
            {
                Product prodTemp = _productRepository.FirstOrDefault(u => u.Id == cartObj.ProductId);
                prodTemp.TempSqMeters = cartObj.SqMeters;
                ProductUserVm.ProductsList.Add(prodTemp);
            }

            return View(ProductUserVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection,ProductUserVM productUserVm )
        {
            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var claim = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier);

            if (User.IsInRole(WebConstants.AdminRole))
            {
                //we need to create an order

               

                OrderHeader orderHeader = new OrderHeader()
                {
                    CreatedByUserId = claim.Value,
                    FinalOrderTotal = productUserVm.ProductsList.Sum(p=>p.TempSqMeters*p.Price),
                    City = productUserVm.ApplicationUser.City,
                    StreetAddress = productUserVm.ApplicationUser.StreetAddress,
                    Country = productUserVm.ApplicationUser.Country,
                    PostalCode = productUserVm.ApplicationUser.PostalCode,
                    FullName = productUserVm.ApplicationUser.FullName,
                    Email = productUserVm.ApplicationUser.Email,
                    PhoneNumber = productUserVm.ApplicationUser.PhoneNumber,
                    OrderDate = DateTime.Now,
                    OrderStatus = WebConstants.StatusPending

                };
                _orderHeaderRepository.Add(orderHeader);
                _orderHeaderRepository.Save();

                foreach (var product in productUserVm.ProductsList)
                {
                    OrderDetail orderDetail = new OrderDetail()
                    {
                        OrderHeaderId = orderHeader.Id,
                        PricePerSqMeter = product.Price,
                        SquareMeter = product.TempSqMeters,
                        ProductId = product.Id
                    };

                    _orderDetailRepository.Add(orderDetail);
                }

                _orderDetailRepository.Save();

                //BrainTree payment transaction request
                string nonceFromTheClient = collection["payment_method_nonce"];

                var request = new TransactionRequest
                {
                    Amount = Convert.ToDecimal(orderHeader.FinalOrderTotal),
                    PaymentMethodNonce = nonceFromTheClient,
                    OrderId = orderHeader.Id.ToString(),
                    Options = new TransactionOptionsRequest
                    {
                        SubmitForSettlement = true
                    }
                };
                var gateway = _brain.GetGateway();

                Result<Transaction> result = gateway.Transaction.Sale(request);

                if (result.Target.ProcessorResponseText == "Approved")
                {
                    orderHeader.TransactionId = result.Target.Id;
                    orderHeader.OrderStatus = WebConstants.StatusApproved;
                }
                else
                {
                    orderHeader.OrderStatus = WebConstants.StatusCancelled;
                }

                _orderHeaderRepository.Save();

                return RedirectToAction(nameof(InquiryConfirmation), new {id=orderHeader.Id});
            }
            else
            {
                //we need to create an inquiry

RoadStones Market/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

using RoadStones_Data.Data.Repository.IRepository;
using RoadStones_Models;
using RoadStones_Utility;

namespace RoadStones_Market.Controllers
{
    [Authorize(WebConstants.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryService;

        public CategoryController(ICategoryRepository categoryService)
        {
            this._categoryService = categoryService;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objList = _categoryService.GetAll();

            return View(objList);
        }

        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category model)
        {
            //Server Validation- Check
            if (!ModelState.IsValid)
            {
                TempData[WebConstants.Error] = "Error while creating category!";
                return View(model);
            }

            _categoryService.Add(model);
            _categoryService.Save();

            TempData[WebConstants.Success] = "Category Created Successfully!";

            return RedirectToAction("Index");
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id==0 || id == null)
            {
                return NotFound();
            }
            var model = _categoryService.Find(id.GetValueOrDefault());

            if (model== null)
            {
                return NotFound();
            }
            return View(model);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category model)
        {
            //Server Validation- Check
            if (!ModelState.IsValid)
            {
                TempData[WebConstants.Error] = "Error while editing category!";
                return View(model);
            }

            _categoryService.Update(model);
            _categoryService.Save();

            TempData[WebConstants.Success] = "Category Edited Successfully!";

            return RedirectToAction("Index");
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var model = _categoryService.Find(id.GetValueOrDefault());

            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var model = _categoryService.Find(id.GetValueOrDefault());

            //Server Validation- Check
            if (model== null)
            {
                return NotFound();
            }

            _categoryService.Remove(model);
            _categoryService.Save();

            TempData[WebConstants.Success] = "Category Deleted Successfully!";
            return RedirectToAction("Index");
        }
    }
}

RoadStones Market/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using RoadStones_Data.Data.Repository.IRepository;
using RoadStones_Models;
using RoadStones_Models.ViewModels;
using WebConstants = RoadStones_Utility.WebConstants;
using RoadStones_Utility;

namespace RoadStones_Market.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class InquiryController : Controller
    {
        [BindProperty]
        public InquiryVM InquiryVm { get; set; }

        private readonly IInquiryHeaderRepository _inquiryHeader;
        private readonly IInquiryDetailsRepository _inquiryDetails;

        public InquiryController(IInquiryDetailsRepository inquiryDetails, IInquiryHeaderRepository inquiryHeader)
        {
            _inquiryDetails = inquiryDetails;
            _inquiryHeader = inquiryHeader;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            InquiryVm = new InquiryVM()
            {
                InquiryHeader = _inquiryHeader.FirstOrDefault(u => u.Id == id),
                InquiryDetails = _inquiryDetails.GetAll(u => u.InquiryHeaderId == id, includeProperties: "Product")
            };

            return View(InquiryVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            InquiryVm.InquiryDetails = _inquiryDetails.GetAll(u => u.InquiryHeaderId == InquiryVm.InquiryHeader.Id);

            foreach (var detail in InquiryVm.InquiryDetails )
            {
                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    ProductId = detail.ProductId
                };

                shoppingCartList.Add(shoppingCart);
            }

            HttpContext.Session.Clear();
            HttpContext.Session.Set(WebConstants.SessionCart,shoppingCartList);
            HttpContext.Session.Set(WebConstants.SessionInquiryId,InquiryVm.InquiryHeader.Id);

            return RedirectToAction("Index","Cart");
        }

        [HttpPost]
        public IActionResult Delete()
        {
            InquiryHeader inquiryHeader = _inquiryHeader.FirstOrDefault(u => u.Id == InquiryVm.InquiryHeader.Id);

            IEnumerable<InquiryDetails> inquiryDetailsEnumerable =
                _inquiryDetails.GetAll(u => u.InquiryHeaderId == InquiryVm.InquiryHeader.Id);

            _inquiryDetails.RemoveRange(inquiryDetailsEnumerable);
            _inquiryHeader.Remove(inquiryHeader);
            _inquiryHeader.Save();

            return RedirectToAction(nameof(Index));
        }

        #region API Calls

        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new {data = _inquiryHeader.GetAll()});
        }


        #endregion

    }
}

RoadStones Market/Views/Shared/_IndividualProductCard.cshtml
@using RoadStones_Utility
@model Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Price.ToString("C")</span> / m²</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WebConstants.ImagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
           
            
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify" >
                <p> @Model.ShortDescription</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

RoadStones Market/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using RoadStones_Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoadStones_Market</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link href="~/FontAwesome/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="images/tile.png" width="40%"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WebConstants.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="False">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                    <div class="dropdown-divider"></div>
                                    @*This pointing to the Razor Page in Area folder*@
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="False">
                                    Order/Inquiry Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a>
                                   
                                </div>
                            </li>
                        }

                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstants.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstants.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-4 pb-4">
        <main role="main" class="pb-3">
            <partial name="_Notifications"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-bottom footer bg-dark">
        <div class="container text-white-50">
            &copy; 2021 - RoadStones_Market @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RoadStones Market/Views/Shared/_Notifications.cshtml
@using RoadStones_Utility

@if (TempData[WebConstants.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WebConstants.Success]');
    </script>
}
@if (TempData[WebConstants.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WebConstants.Error]');
    </script>
}